name: CI
on: [push]
jobs:
  unit-tests:
    runs-on: [self-hosted, ec2, squad]
    steps:
    - name: Pull repository
      uses: actions/checkout@v1
    - name: Run composer install
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Stop the Post Scriptum
      run: docker stop ps-server || true  && docker rm ps-server || true
    - name: Install & start Post Scriptum server
      run: docker run -d --net=bridge --volume=$PWD/tests/ServerFolder:/home/steam/squad-dedicated -e PORT=7787 -e QUERYPORT=27165 -e RCONPORT=21114 --name=ps-server avilcreeggan/post-scriptum
    - name: Wait for Post Scriptum Server to start up
      run: chmod +x .github/waitForServerStartup.sh && ./.github/waitForServerStartup.sh
    - name: Wait for Post Scriptum Server to fully boot
      run: sleep 60
    - name: Log PostScriptum Server
      run: docker logs ps-server
    - name: Run PHPUnit
      run: rm -f coverage.xml && vendor/bin/phpunit --coverage-clover=coverage.xml
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t $PostScriptumRconPHPCodecovToken
    - name: Stop the Post Scriptum Server
      run: docker stop ps-server || true
