name: CI
on: [push]
jobs:
  unit-tests:
    runs-on: [self-hosted, linux, x64, ec2]
    steps:
    - name: Pull repository
      uses: actions/checkout@v1
    - name: Run composer install
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Stop the Post Scriptum
      run: docker stop ps-server || true  && docker rm ps-server || true
    - name: Create the ps-server container and install the server
      run: docker run -d --net=bridge -e PORT=7787 -e QUERYPORT=27165 -e RCONPORT=21114 --name=ps-server avilcreeggan/post-scriptum
    - name: Wait for Post Scriptum Server to start up
      run: chmod +x .github/waitForServerStartup.sh && ./.github/waitForServerStartup.sh
    - name: Stop the container
      run: docker stop ps-server
    - name: Add the correct Rcon.cfg
      run: docker cp $PWD/tests/ServerFolder/PostScriptum/ServerConfig/Rcon.cfg ps-server:/home/steam/post-scriptum-dedicated/PostScriptum/ServerConfig/Rcon.cfg
    - name: Re-start the ps-server container
      run: docker start ps-server
    - name: Wait for Post Scriptum Server to start up
      run: chmod +x .github/waitForServerStartup.sh && ./.github/waitForServerStartup.sh
    - name: Wait for Post Scriptum Server to fully boot
      run: sleep 60
    - name: Log PostScriptum Server
      run: docker logs ps-server
    - name: Run PHPUnit
      run: rm -f coverage.xml && vendor/bin/phpunit --coverage-clover=coverage.xml
    - name: Upload coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
    - name: Stop the Post Scriptum Server
      run: docker stop ps-server || true
